# --- GUI Settings ---
APP_TITLE = "RoTWK Mod Switcher - v."
INITIAL_WINDOW_SIZE = "1200x1200"

# LORD OF THE RINGS THEMED COLORS
TEXT_PRIMARY = "#b99767"
TEXT_SECONDARY = "#D3D3D3"
BUTTON_PRIMARY_BG = "#34474b"
BUTTON_SECONDARY_BG = "#42575a"
BUTTON_PRIMARY_BORDER = "#b99767"
BUTTON_PRIMARY_HOVER = "#5d6f6d"
BUTTON_SECONDARY_HOVER = "#112222"
BUTTON_TEXT_PRIMARY = "#FFD700"
BUTTON_TEXT_SECONDARY = "#112222"
BUTTON_TERTIARY_BG = "#26383c"

PRIMARY_BUTTON_FONT = ("Arial", 20, "bold")
SECONDARY_BUTTON_FONT = ("Arial", 16, "bold")
TERTIARY_BUTTON_FONT = ("Arial", 16)
LABEL_FONT = ("Arial", 14, "bold")
FLAG_FONT = ("Arial", 15, "bold")
TEXT_FONT = ("Arial", 16)