# --- GUI Settings ---
APP_TITLE = "RoTWK TROWMod Switcher"
INITIAL_WINDOW_SIZE = "1100x980"
ICON_FILE_PATH = "src/rotwk_trowmod_switcher/assets/app_icon.ico"
BG_IMG_FILE_PATH = "src/rotwk_trowmod_switcher/assets/bg_ai_gen.jpeg"
GAME_IMG_FILE_PATH = "src/rotwk_trowmod_switcher/assets/game_icon.png"

# LORD OF THE RINGS THEMED DARK PALETTE
APP_SURFACE = "#101719"
PANEL_SURFACE = "#172326"
PANEL_RAISED = "#1d2c2e"
INPUT_SURFACE = "#0d1416"
TEXT_PRIMARY = "#d8b678"
TEXT_SECONDARY = "#d7dedc"
TEXT_MUTED = "#849391"
ACCENT_GREEN = "#6fa38d"
BUTTON_PRIMARY_BG = "#365b55"
BUTTON_SECONDARY_BG = "#28453f"
BUTTON_PRIMARY_BORDER = "#8e744b"
BUTTON_PRIMARY_HOVER = "#47766a"
BUTTON_SECONDARY_HOVER = "#396057"
BUTTON_TEXT_PRIMARY = "#f4e7c4"
BUTTON_TEXT_SECONDARY = "#e4ece8"
BUTTON_TERTIARY_BG = "#223437"
DIVIDER_COLOR = "#304345"

PRIMARY_BUTTON_FONT = ("Arial", 16, "bold")
SECONDARY_BUTTON_FONT = ("Arial", 15, "bold")
TERTIARY_BUTTON_FONT = ("Arial", 13)
LABEL_FONT = ("Arial", 13, "bold")
FLAG_FONT = ("Arial", 13, "bold")
TEXT_FONT = ("Arial", 14)
STATUS_FONT = ("Arial", 12, "bold")
